### ISSUE TITLE
bug: searches with a leading or trailing space will not be found

### ISSUE THREAD

**Issue by futuremihai** [peercoin/perpera-web#13]
When copy pasting a hash from a webpage or otherwise, if there is a space before or after the hash, it will not register.

This can be fixed with a simple filter to exclude non-hash characters. (could potentially be a DoS attack vector too)

**Comment by peerchemist** [comment]
Fixed with https://github.com/peercoin/perpera-web/commit/60ec392a8a7cf91a7f0a394d2286e8584ee0b017
