### ISSUE TITLE
Icons for document/uri add

### ISSUE THREAD

**Issue by peerchemist** [peercoin/perpera-web#26]
Icons for add file / add uri on the right look generic and ugly.

![image](https://user-images.githubusercontent.com/7818961/72890348-f4dbb800-3d11-11ea-916e-9e413b49c58b.png)

I propose to:

* make them vertical, one down one up
* fix mobile layout for those
* use new icons, attached bellow

Here are new icons in svg format:
[attach_icons.zip](https://github.com/peercoin/perpera-web/files/4096836/attach_icons.zip)

**Comment by bananenwilly** [comment]
https://github.com/peercoin/perpera-web/pull/30
